steps:
  # Update environment variable for Audio Bucket name
- name: gcr.io/cloud-builders/gcloud
  args:
    - beta
    - runtime-config
    - configs
    - variables
    - set
    - AUDIO_BUCKET
    - apigeeaudiobucket
    - --config-name=apigeeDemo
    - --is-text
  # Update environment variable for Text Bucket name
- name: gcr.io/cloud-builders/gcloud
  args:
    - beta
    - runtime-config
    - configs
    - variables
    - set
    - TEXT_BUCKET
    - apigeetextbucket
    - --config-name=apigeeDemo
    - --is-text
  # Deploy Cloud Function
- name: gcr.io/cloud-builders/gcloud
  args:
    - functions
    - deploy
    - speechAPIGateway
    - --stage-bucket=apigeestagebucket
    - --trigger-bucket=apigeeaudiobucket